[versions]
agp = "8.9.2"
kotlin = "2.1.20"
compileSdk = "35"
minSdk = "26"
targetSdk = "35"
androidxCore = "1.15.0"
appcompat = "1.7.0"
webkit = "1.12.1"
junit = "4.13.2"
json = "20251224"
androidxTestExt = "1.2.1"
androidxTestCore = "1.6.1"
androidxTestRunner = "1.6.2"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
junit = { module = "junit:junit", version.ref = "junit" }
json-jvm = { module = "org.json:json", version.ref = "json" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
